**Tipos de estructuras**

In [42]:
#variable numericas
2+2

x = 2
y = 1
z = 4

fx = x*x + y - z

X*x + y - z

1

In [43]:
#Variables cadena

a = "perro"
b = "gato"
c = "leones"

print("Lista de animales",a)

Lista de animales perro

In [44]:
#booleanos
r = True

True and False
True or True

True

**Trabajando con matrices**

In [ ]:
#Operaciones básicas
x = 20
y = 6

x+y
x-y
x*y
x/y

x**6

#Vectores
vec1 = [1,2,3,4,5]
vec2 = [3,6,9,12,15]

vec1+vec2
vec1*vec2

In [2]:
##Modulo Numpy (algebra e matrices)
import numpy as np

In [3]:
a = np.array([2,3,4])
b = np.array([10,20,30])

print("Número de elementos de a = ",a.size)

Número de elementos de a =  3

In [17]:
a+5
b*b

a+b
a-b
a*b
b/a

array([5.        , 6.66666667, 7.5       ])

In [21]:
b/a

array([5.        , 6.66666667, 7.5       ])

In [22]:
A = np.array([[2,3,4],
              [20,30,40]])

B = np.array([[3,3],
             [13,16],
             [4,4]])

In [25]:
#a.size #Para ver la cantidad de elementos
#A.size #Para ver la cantidad de elementos
A.shape #Para ver la dimensión
#B.shape

(2, 3)

In [26]:
A@B #Multiplicación de matrices

array([[ 61,  70],
       [610, 700]])

In [32]:
#Operaciones con matrices
B[1]
#A[0]*20
#A[0] = A[0]*20

array([13, 16])

In [33]:
#Calculanddo la norma de un vector
x = np.array([2,4,6,8])
y = np.arange(1,5)

In [37]:
sum(x*y) #Producto escalar
np.sqrt(x@x)#Calculamos la norma de un vector

10.954451150103322

**CICLOS**

In [ ]:
#ciclos
suma = 0
for i in 2,4,6,8:
    suma = suma+i
    print(suma)

for i in range(2,8):
    print(i)

**FUNCIONES**

In [ ]:
#Funcion muy util              
range(1,10)


suma = 0
for i in 2,4,6,8:
    suma = suma + i
    print(suma)


#Funciones
def fun_sum(n):
    s = n*(n+1)/2
    print(s)

def trian(b,h):
    area = b*h/2
    print(area)

trian(4,6)


def producto(n1,n2):
    prod = n1*10 + n2
    if prod == 23:
        print("galleta")
    elif prod == 20:
        print("gaseosa")
    else:
        print("No hay producto")

In [4]:
#Sample
from random import sample #Paquete de muestreo
import random

In [5]:
lista1 = [1,2,3,4,5,6,7,8,9,10]
random.sample(lista1,3)

[10, 4, 6]

In [6]:
set1 = ["perro","gato","conejo","caballo","jirafa"]
random.sample(set1,4)

['perro', 'conejo', 'caballo', 'gato']

In [9]:
muestra = list()

In [11]:
for x in range(1,61):
    persona = random.sample(range(18,65),1)
    muestra.append(persona)

In [13]:
len(muestra)

60

In [23]:
#Clase: Plantilla generica que permitira crear muchos objetos
class Lapiz:
    color = 'amarillo'
    tiene_borrador = False
    tiene_grafito = True
    
class Lapiz:
    color = 'amarillo'
    tiene_borrador = False
    tiene_grafito = True
    def dibujar(self):
        print("El lapiz esta dibujando")

In [33]:
#Objeto: lapiz_cesar es una instancia de Lapiz
lapiz_cesar = Lapiz()
lapiz_milagros = Lapiz()

In [26]:
lapiz_cesar.tiene_borrador
lapiz_milagros.tiene_borrador

lapiz_cesar.dibujar()
lapiz_milagros.dibujar()

El lapiz esta dibujando
El lapiz esta dibujando

In [27]:
class Lapiz:
    color = 'amarillo'
    tiene_borrador = False
    tiene_grafito = True
    def dibujar(self):
        print("El lapiz esta dibujando")
    def borrar(self):
        if self.valido_borrar():
            print("El lapiz esta borrando")
        else:
            print("El lapiz no tiene borrador")
    def valido_borrar(self):
        return self.tiene_borrador

In [31]:
lapiz_cesar.borrar()
lapiz_milagros.borrar()

El lapiz esta borrando
El lapiz no tiene borrador

In [30]:
lapiz_cesar.tiene_borrador = True

In [36]:

#Practicando con clases y objetos:
#===#===#===#===#===#===#===#===#===#===
#===#===#===#===#===#===#===#===#===#===
class Lapiz:
    def __init__(self, col,borr,tiene):
        self.color = col
        self.tiene_borrador = borr
        self.Tiene_grafito = tiene       
    
    def dibujar(self):
        print("El lapiz esta dibujando")
    def borrar(self):
        if self.valido_borrar():
            print("El lapiz esta borrando")
        else:
            print("El lapiz no tiene borrador")
        
    def valido_borrar(self):
        return self.tiene_borrador

In [37]:
lapiz_cesar = Lapiz('verde',False,True)

In [38]:
lapiz_cesar.color

'verde'

In [ ]:
#Llamando objetos
lapiz_cesar = lapiz()

#Llamando caracteristicas
lapiz_cesar.color
lapiz_cesar.tiene_borrador
lapiz_cesar.Tiene_grafito

lapiz_cesar.dibujar()
lapiz_cesar.borrar()

lapiz_cesar.tiene_borrador = True

lapiz_cesar.borrar()


lapiz_cesar = lapiz('azul',True,True)

lapiz_cesar.color
lapiz_cesar.borrar()

**DATA FRAMES**

In [39]:
#Trabajando con bases de datos
import pandas as pd

In [220]:
datos = pd.read_csv('C:/Users/Cesar Quezada/Dropbox/Cursos DMC/Cursos Univeritarios/Python para Universitarios/Grupo 02/Base Credit Card.csv')
datos

,ID_CLIENTE,ANTIGUEDAD_MESES,TIPO_TARJETA,LINEA_CREDITO,RNG_LINEA,DEUDA_TARJETA,SEGMENTO_BANCO,AMBITO,ZONA,EDAD,SEXO,ECIVIL,Total_facturacion,Num_compras
0,C0000001,R4. [24-MAS>,CLASICA,30000,30000,0.00,SEGMENTO BRONCE,L,CALLAO,65.0,M,CASADO,478.80,1
1,C0000002,R4. [24-MAS>,CLASICA,21000,22000,0.00,SEGMENTO ORO,L,MODERNA,67.0,F,SOLTERO,1374.15,3
2,C0000004,R4. [24-MAS>,CLASICA,31500,32000,115.16,SEGMENTO ORO,L,MODERNA,93.0,M,CASADO,1016.52,8
3,C0000006,R4. [24-MAS>,CLASICA,10800,12000,1805.19,SEGMENTO PLATA,L,MODERNA,NaN,M,CASADO,2093.00,16
4,C0000007,R4. [24-MAS>,CLASICA,18000,18000,17918.60,SEGMENTO PLATA,L,MODERNA,NaN,M,CASADO,3176.38,13
5,C0000008,R4. [24-MAS>,CLASICA,15750,16000,7371.50,SEGMENTO PLATA,L,MODERNA,NaN,M,CASADO,4388.14,3
6,C0000009,R4. [24-MAS>,CLASICA,3600,4000,145.00,SEGMENTO ORO,L,MODERNA,NaN,F,SOLTERO,1642.49,19
7,C0000012,R4. [24-MAS>,CLASICA,24000,24000,417.08,SEGMENTO PLATA,L,MODERNA,57.0,M,CASADO,1162.09,15
8,C0000013,R4. [24-MAS>,CLASICA,14400,16000,3820.13,SEGMENTO ORO,L,MODERNA,65.0,M,SOLTERO,393.20,2
9,C0000014,R4. [24-MAS>,CLASICA,16800,18000,0.00,SEGMENTO BRONCE,L,MODERNA,51.0,M,CASADO,1483.28,7
10,C0000016,R4. [24-MAS>,CLASICA,25900,26000,3515.76,SEGMENTO PLATA,L,MODERNA,NaN,M,CASADO,25.00,1
11,C0000017,R4. [24-MAS>,CLASICA,7500,8000,0.00,SEGMENTO PLATA,L,CENTRO,56.0,M,SOLTERO,671.92,6
12,C0000018,R4. [24-MAS>,CLASICA,10800,12000,1353.94,SEGMENTO PLATA,L,MODERNA,NaN,M,CASADO,1706.80,4
13,C0000020,R4. [24-MAS>,CLASICA,28800,30000,20984.26,SEGMENTO PLATA,L,MODERNA,57.0,F,DIVORCIADO,3976.13,22
14,C0000021,R4. [24-MAS>,CLASICA,30000,30000,365.00,SEGMENTO BRONCE,L,MODERNA,66.0,M,CASADO,516.00,2
15,C0000022,R4. [24-MAS>,CLASICA,17280,18000,429.61,SEGMENTO PLATA,L,MODERNA,76.0,M,SOLTERO,156.00,6
16,C0000023,R4. [24-MAS>,CLASICA,19440,20000,1061.83,SEGMENTO PLATA,L,MODERNA,NaN,M,CASADO,3422.80,21
17,C0000025,R4. [24-MAS>,CLASICA,24000,24000,10321.31,SEGMENTO PLATA,L,SUR,63.0,M,CASADO,3367.60,24
18,C0000026,R4. [24-MAS>,CLASICA,14700,16000,2243.58,SEGMENTO ORO,P,PROVINCIA,57.0,M,CASADO,412.44,3
19,C0000027,R4. [24-MAS>,CLASICA,34550,36000,5410.19,SEGMENTO ORO,L,MODERNA,56.0,F,CASADO,4447.34,24
20,C0000028,R4. [24-MAS>,CLASICA,38800,40000,149.22,SEGMENTO ORO,L,NORTE,39.0,M,CASADO,11392.75,27
21,C0000029,R4. [24-MAS>,CLASICA,24000,24000,0.74,SEGMENTO ORO,L,MODERNA,45.0,M,SOLTERO,274.89,1
22,C0000031,R4. [24-MAS>,CLASICA,32400,34000,6367.81,SEGMENTO PLATA,L,MODERNA,51.0,M,CASADO,2381.67,5
23,C0000034,R4. [24-MAS>,CLASICA,10125,12000,487.85,SEGMENTO BRONCE,L,MODERNA,NaN,M,CASADO,499.00,1
24,C0000035,R4. [24-MAS>,CLASICA,9900,10000,41.66,SEGMENTO ORO,L,MODERNA,NaN,F,CASADO,291.58,9
25,C0000038,R4. [24-MAS>,CLASICA,5400,6000,802.91,SEGMENTO PLATA,L,MODERNA,NaN,F,SOLTERO,924.73,1
26,C0000039,R4. [24-MAS>,CLASICA,18000,18000,6447.23,SEGMENTO PLATA,L,SUR,NaN,M,SOLTERO,2018.76,12
27,C0000041,R4. [24-MAS>,CLASICA,10800,12000,3461.57,SEGMENTO PLATA,L,NORTE,49.0,M,CASADO,14458.50,7
28,C0000042,R4. [24-MAS>,CLASICA,18000,18000,0.00,SEGMENTO BRONCE,L,ESTE,44.0,F,SOLTERO,466.20,7
29,C0000043,R4. [24-MAS>,CLASICA,10000,10000,10.00,SEGMENTO PLATA,L,MODERNA,49.0,F,DIVORCIADO,6633.74,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1190,C0002355,R4. [24-MAS>,CLASICA,12750,14000,57.50,SEGMENTO PLATA,L,CENTRO,41.0,M,CASADO,495.28,5
1191,C0002356,R4. [24-MAS>,CLASICA,10000,10000,241.03,SEGMENTO ORO,L,MODERNA,51.0,M,CASADO,1971.40,21
1192,C0002357,R4. [24-MAS>,CLASICA,15900,16000,439.11,SEGMENTO PLATA,L,MODERNA,36.0,F,SOLTERO,5981.07,30
1193,C0002358,R4. [24-MAS>,CLASICA,4000,4000,4101.57,SEGMENTO PLATA,L,MODERNA,30.0,F,SOLTERO,2627.43,10
1194,C0002360,R4. [24-MAS>,CLASICA,21600,22000,0.00,SEGMENTO PLATA,L,MODERNA,52.0,F,SOLTERO,122.50,2
1195,C0002366,R4. [24-MAS>,CLASICA,2700,4000,937.80,SEGMENTO PLATA,L,MODERNA,40.0,M,SOLTERO,1905.29,6
1196,C0002367,R4. [24-MAS>,CLASICA,10500,12000,1442.82,SEGMENTO PLATA,L,MODERNA,51.0,M,CASADO,100.00,1
1197,C0002368,R4. [24-MAS>,CLASICA,8000,8000,56.50,SEGMENTO BRONCE,L,MODERNA,50.0,F,SOLTERO,156.00,6
1198,C0002370,R4. [24-MAS>,CLASICA,2000,2000,1946.34,SEGMENTO PLATA,L,NORTE,45.0,M,CASADO,550.20,4
1199,C0002375,R4. [24-MAS>,ORO,15000,16000,505.83,SEGMENTO PLATA,L,MODERNA,50.0,M,CASADO,7074.90,17
1200,C0002376,R4. [24-MAS>,CLASICA,5400,6000,763.82,SEGMENTO PLATA,L,MODERNA,54.0,F,SOLTERO,1890.29,8
1201,C0002379,R4. [24-MAS>,ORO,6000,6000,-3.09,SEGMENTO PLATA,L,MODERNA,36.0,M,SOLTERO,1156.03,16
1202,C0002380,R4. [24-MAS>,ORO,5000,6000,4672.72,SEGMENTO ORO,L,MODERNA,60.0,M,DIVORCIADO,438.28,8
1203,C0002383,R4. [24-MAS>,CLASICA,1000,2000,500.47,SEGMENTO PLATA,L,NORTE,39.0,M,SOLTERO,350.00,2
1204,C0002389,R4. [24-MAS>,CLASICA,5200,6000,432.77,SEGMENTO BRONCE,L,CENTRO,43.0,M,SOLTERO,1884.26,20
1205,C0002390,R4. [24-MAS>,ORO,5685,6000,5364.94,SEGMENTO PLATA,L,CENTRO,53.0,F,SOLTERO,1210.41,10
1206,C0002391,R4. [24-MAS>,ORO,10000,10000,9306.75,SEGMENTO ORO,L,MODERNA,55.0,M,SOLTERO,4272.56,13
1207,C0002393,R4. [24-MAS>,ORO,15000,16000,1762.35,SEGMENTO PLATA,L,NORTE,36.0,M,SOLTERO,392.70,1
1208,C0002395,R3. [12-24 M>,PLATINUM,10000,10000,65.10,SEGMENTO ORO,L,CENTRO,44.0,M,CASADO,5702.20,8
1209,C0002396,R3. [12-24 M>,CLASICA,16000,16000,7919.69,SEGMENTO BRONCE,L,MODERNA,NaN,M,SOLTERO,9832.44,31
1210,C0002397,R3. [12-24 M>,ORO,3500,4000,1472.65,SEGMENTO ORO,L,MODERNA,54.0,M,CASADO,50.00,1
1211,C0002401,R3. [12-24 M>,ORO,3000,4000,36.76,SEGMENTO BRONCE,L,MODERNA,26.0,F,SOLTERO,110.28,1
1212,C0002407,R2. [6-12 M>,ORO,3000,4000,1521.44,SEGMENTO ORO,L,NORTE,42.0,M,CASADO,1670.34,2
1213,C0002408,R2. [6-12 M>,CLASICA,800,2000,0.00,SEGMENTO BRONCE,L,CENTRO,35.0,F,SOLTERO,119.00,1
1214,C0002409,R1. <0-6 M>,CLASICA,1500,2000,1380.00,SEGMENTO BRONCE,L,MODERNA,26.0,F,SOLTERO,1380.00,1
1215,C0002410,R1. <0-6 M>,ORO,3000,4000,0.00,SEGMENTO PLATA,L,MODERNA,25.0,M,SOLTERO,1051.10,5
1216,C0002412,R4. [24-MAS>,CLASICA,30000,30000,0.00,SEGMENTO ORO,L,CENTRO,NaN,F,CASADO,645.58,1
1217,C0002414,R4. [24-MAS>,CLASICA,25900,26000,2590.93,SEGMENTO PLATA,L,CENTRO,65.0,F,CASADO,3019.17,24
1218,C0002416,R4. [24-MAS>,CLASICA,19200,20000,4533.89,SEGMENTO PLATA,L,MODERNA,38.0,M,CASADO,7592.74,14
1219,C0002420,R4. [24-MAS>,ORO,17500,18000,11228.45,SEGMENTO PLATA,L,MODERNA,53.0,M,CASADO,3878.08,16

In [ ]:
datos.dtypes

datos["LINEA_CREDITO"].describe()

datos["ECIVIL"].describe()

datos["LINEA_CREDITO"].mean()
datos["LINEA_CREDITO"].min()
datos["LINEA_CREDITO"].max()
datos["LINEA_CREDITO"].std()

datos.groupby("ECIVIL").size()
datos.groupby("ZONA").size()

pd.crosstab(datos["ECIVIL"],datos["ZONA"])
pd.crosstab(datos["ECIVIL"],datos["SEXO"]) #Cruce simple de variables

**Viendo más ..**

In [ ]:
#TECNICAS DE PRE PROCESAMIENTO CON PYTHON
#==#==#==#==#==#==#==#==#==#==
#==#==#==#==#==#==#==#==#==#==
#Identificar missing values
#Normalización de datos 
#Data binning (creacion de categorías para variables numéricas)

In [ ]:
#Identificar missing values
#==#==#==#==#==#==#==#==#==#==
import pandas as pd #Importamos el paquete pandas con alias pd
import numpy as np #Importamos el paquete numpy con alias np

In [63]:
datos["EDAD"].describe()
datos["EDAD"].head(10)

0    65.0
1    67.0
2    93.0
3     NaN
4     NaN
5     NaN
6     NaN
7    57.0
8    65.0
9    51.0
Name: EDAD, dtype: float64

In [145]:
#Vemos presencia de valores perdidos
datos.loc[(pd.isna(datos["EDAD"]))].shape[0]/datos["EDAD"].shape[0]*100

0.0

In [207]:
datos.head(10)

,ID_CLIENTE,ANTIGUEDAD_MESES,TIPO_TARJETA,LINEA_CREDITO,RNG_LINEA,DEUDA_TARJETA,SEGMENTO_BANCO,AMBITO,ZONA,EDAD,SEXO,ECIVIL,Total_facturacion,Num_compras
0,C0000001,R4. [24-MAS>,CLASICA,30000,30000,0.00,SEGMENTO BRONCE,L,CALLAO,65.0,M,CASADO,478.80,1
1,C0000002,R4. [24-MAS>,CLASICA,21000,22000,0.00,SEGMENTO ORO,L,MODERNA,67.0,F,SOLTERO,1374.15,3
2,C0000004,R4. [24-MAS>,CLASICA,31500,32000,115.16,SEGMENTO ORO,L,MODERNA,93.0,M,CASADO,1016.52,8
3,C0000006,R4. [24-MAS>,CLASICA,10800,12000,1805.19,SEGMENTO PLATA,L,MODERNA,NaN,M,CASADO,2093.00,16
4,C0000007,R4. [24-MAS>,CLASICA,18000,18000,17918.60,SEGMENTO PLATA,L,MODERNA,NaN,M,CASADO,3176.38,13
5,C0000008,R4. [24-MAS>,CLASICA,15750,16000,7371.50,SEGMENTO PLATA,L,MODERNA,NaN,M,CASADO,4388.14,3
6,C0000009,R4. [24-MAS>,CLASICA,3600,4000,145.00,SEGMENTO ORO,L,MODERNA,NaN,F,SOLTERO,1642.49,19
7,C0000012,R4. [24-MAS>,CLASICA,24000,24000,417.08,SEGMENTO PLATA,L,MODERNA,57.0,M,CASADO,1162.09,15
8,C0000013,R4. [24-MAS>,CLASICA,14400,16000,3820.13,SEGMENTO ORO,L,MODERNA,65.0,M,SOLTERO,393.20,2
9,C0000014,R4. [24-MAS>,CLASICA,16800,18000,0.00,SEGMENTO BRONCE,L,MODERNA,51.0,M,CASADO,1483.28,7

In [40]:
datos["EDAD2"] = datos["EDAD"]
media = datos["EDAD"].mean() #Calculamos la media
datos["EDAD2"] = datos["EDAD2"].replace(np.nan,media) #Reemplazamos los NAs por la media

NameError: name 'datos' is not defined

In [ ]:
#Normalización de datos 
#==#==#==#==#==#==#==#==#==#==

datos["LINEA_CREDITO"].mean() #Obtenemos el promedio de la variable Linea de crédito
datos["LINEA_CREDITO"].min() #Obtenemos el mínimo de la variable Linea de crédito
datos["LINEA_CREDITO"].max() #Obtenemos el máximo de la variable Linea de crédito
datos["LINEA_CREDITO"].std() #Obtenemos la desviación estandar de la variable Linea de crédito


datos["LINEA_CREDITO_N"] = (datos["LINEA_CREDITO"]-datos["LINEA_CREDITO"].mean())/datos["LINEA_CREDITO"].std()

datos.dtypes

datos2.info

In [100]:
#Data binning (creacion de categorías para variables numéricas)
#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==#==
rango = int((datos["LINEA_CREDITO"].max() - datos["LINEA_CREDITO"].min())/4) #Separamos los rangos
bins = range(datos["LINEA_CREDITO"].min(),datos["LINEA_CREDITO"].max(),rango) #Obtenemos los cortes
grupos = ["rango01","rango02","rango03","rango04"] #Nombramos las etiquetas

#datos.bins = pd.cut(datos["LINEA_CREDITO"],bins,labels = grupos)

In [41]:
# Función de Identificar Outliers:
#================================
def calcularOutliars(x):
  Q01 = x.quantile(0.25)
  Q03 = x.quantile(0.75)
  IQR = Q03 - Q01
  a = (x < (Q01 - 1.5 * IQR)) | (x > (Q03 + 1.5 * IQR))
  numOutliars = a[a == True].shape[0]
  return numOutliars

In [42]:
#Calculamos el % de outliars en las variables numéricas
for x in datos.columns:
    print(x)
    print(calcularOutliars(datos[x])/datos[x].shape[0]*100,"%")
    print("\n")
datos.describe()

NameError: name 'datos' is not defined

In [ ]:
#Calculamos el % de outliars en las variables numéricas
calcularOutliars(datos['EDAD2'])

In [ ]:
#Imputamos los valores outliers en nuevas variables
#==================================================
#creamos la función de reemplazo de outliers
def fun_rep(num): 
    if num > LS: 
        return LS
    elif num < LI and num > 0: 
        return LI
    else: 
        return num

In [ ]:
#Variable edad
Q01 = datos["EDAD2"].quantile(0.25)
Q03 = datos["EDAD2"].quantile(0.75)
IQR = Q03 - Q01
LS = Q03 + 1.5 * IQR
LI = Q01 - 1.5 * IQR

datos["EDAD2_im"] = datos["EDAD2"].apply(fun_rep)

In [ ]:
datos['EDAD_im'].describe()
datos['EDAD'].describe()

**ANALISIS GRÁFICO**

In [102]:

#ANALISIS GRAFICO
#==#==#==#==#==#==#==#==#==#==
#==#==#==#==#==#==#==#==#==#==
import seaborn as sns #Cargamos el paquete seaborn con alias sns
import matplotlib.pyplot as plt #importamos la libreria pyplot con alias plt
import numpy as np
import math as mt
import pylab as pl

#GRaficando una función
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
fx = x*x

plt.figure(figsize=(16,5), dpi=100)
#plt.plot(x,fx)  #Graficamos la función generada
#plt.xlabel("eje x")
#plt.ylabel("eje y")
#plt.title("Mi primera gráfica")
#plt.legend()

In [ ]:
plt.figure(figsize=(16,5), dpi=100)
plt.plot(x,fx)  #Graficamos la función generada
plt.xlabel("eje x")
plt.ylabel("eje y")
plt.title("Mi primera gráfica")
plt.legend()

plt.plot(x,fx,'red',label='Función x')  #Graficamos la función generada
plt.xlabel("eje x")
plt.ylabel("eje y")
plt.title("Mi primera gráfica")
plt.legend()

plt.plot(x,fx,'o',label='Función x')  #Graficamos la función generada
plt.xlabel("eje x")
plt.ylabel("eje y")
plt.title("Mi primera gráfica")
plt.legend()

plt.plot(x,fx,'or',label='Función x')  #Graficamos la función generada
plt.xlabel("eje x")
plt.ylabel("eje y")
plt.title("Mi primera gráfica")
plt.legend()

In [ ]:
#####TIPOS DE GRÁFICOS
#######################

#diagrama de dispersión
plt.scatter(datos["EDAD"],datos["LINEA_CREDITO"],c = "g") 
plt.title("Edades vs Linea de credito")
plt.xlabel("Edades")
plt.ylabel("Linea de credito")


#Histograma de las Edades
plt.hist(datos["LINEA_CREDITO"],facecolor = "y",bins = 60)
plt.title("Linea de credito")
plt.grid("True") #Mostramos las grillas


#Diagrama de caja
plt.subplot(2,2,4)
plt.boxplot(datos["EDAD"])
plt.title("Diagrama de caja")


#==========================================================
plt.figure()

plt.subplot(1,2,1)
plt.scatter(datos["EDAD"],datos["LINEA_CREDITO"],c = "g") 
plt.show()

plt.subplot(1,2,2)
plt.hist(datos["LINEA_CREDITO"],facecolor = "y",bins = 60)
plt.show()

#==========================================================



#Correlación grafica a partir de regresión
plt.subplot(2,2,3)
sns.regplot(x = "EDAD",y = "LINEA_CREDITO",data = datos) 
plt.ylim(0,)

**CLUSTER K MEANS**
*http://www.aprendemachinelearning.com/k-means-en-python-paso-a-paso/*

In [45]:
from sklearn.cluster import KMeans

In [126]:
nombres = ["LINEA_CREDITO","DEUDA_TARJETA","Total_facturacion"]

x_train = np.array(datos[nombres])
y_train = np.array(datos["Num_compras"])

In [46]:
kmeans = KMeans(n_clusters = 5)
kmeans.fit(x_train)

kmeans.cluster_centers_

NameError: name 'x_train' is not defined

In [133]:
kmeans = KMeans(n_clusters = 4)
kmeans.fit(x_train)
kmeans.fit(x_train).score(x_train)

kmeans.predict(x_train)

array([1, 1, 1, ..., 1, 3, 3])

In [ ]:
plt.boxplot(datos["EDAD"])

In [44]:
#Obteniendo el nro de centros para el cluster
Nc = range(1, 20)
kmeans = [KMeans(n_clusters=i) for i in Nc]
kmeans
score = [kmeans[i].fit(x_train).score(x_train) for i in range(len(kmeans))]
score
plt.plot(Nc,score)
plt.xlabel('Number of Clusters')
plt.ylabel('Score')
plt.title('Elbow Curve')
plt.show()

NameError: name 'KMeans' is not defined

**ARBOLES DE DECISION**

In [224]:
from sklearn import tree
from sklearn.metrics import f1_score, precision_score, recall_score, auc

In [221]:
nomb2 = ["LINEA_CREDITO","DEUDA_TARJETA"]

x_train = datos[nomb2]
y_train = datos["SEXO"]

In [222]:
tree01 = tree.DecisionTreeClassifier()
class01 = tree01.fit(x_train,y_train)

pred01 = tree01.predict(x_train)

In [227]:
prediction_train = tree01.score(x_train, y_train)

In [228]:
prediction_train

0.9663934426229508

In [47]:
pred01

NameError: name 'pred01' is not defined

**REGRESION LINEAL**

In [138]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import seaborn as sns

In [229]:
datos = pd.read_csv('C:/Users/Cesar Quezada/Dropbox/Cursos DMC/Cursos Univeritarios/Python para Universitarios/Grupo 02/Base ciudades.csv')
datos

                  Country  Life_expentacy           GDP    HIV
0                 Algeria          73.131   6406.816621   0.10
1                  Angola          51.093   5519.183179   2.00
2               Argentina          75.901  15741.045770   0.50
3                 Armenia          74.241   4748.928585   0.10
4               Australia          81.907  34642.388130   0.10
5                 Austria          80.854  36871.071350   0.30
6              Azerbaijan          70.739   9387.389497   0.10
7                 Bahamas          75.620  21470.804200   3.10
8              Bangladesh          68.944   1669.874271   0.06
9                Barbados          76.835  16173.650090   1.40
10                Belarus          70.349  13224.027290   0.30
11                Belgium          80.009  33047.962420   0.20
12                 Belize          76.072   7255.005226   2.30
13                  Benin          56.081   1457.215648   1.20
14                 Bhutan          67.185   5640.904567   0.20
15                Bolivia          66.618   4171.368213   0.20
16               Botswana          53.183  13625.115380  24.80
17                 Brazil          73.488  10373.406370   0.45
18               Bulgaria          73.371  11285.566660   0.10
19           Burkina_Faso          55.439   1343.485463   1.20
20                Burundi          50.411    484.148644   3.30
21               Cambodia          63.125   1949.589584   0.50
22               Cameroon          51.610   2033.232876   5.30
23                 Canada          81.012  35689.571190   0.20
24   Central_African_Rep.          48.398    694.721669   4.70
25                   Chad          49.553   1745.674492   3.40
26                  Chile          79.120  14620.872510   0.40
27                  China          73.456   8848.092267   0.10
28               Colombia          73.703   7767.635065   0.50
29                Comoros          61.061   1023.898606   0.10
..                    ...             ...           ...    ...
117                Serbia          74.522   9719.433468   0.10
118          Sierra_Leone          47.794    924.408330   1.60
119             Singapore          81.126  49683.267100   0.10
120       Slovak_Republic          75.446  20364.907990   0.06
121              Slovenia          79.341  24873.731920   0.06
122               Somalia          51.219    943.035454   0.70
123          South_Africa          52.797   9482.090663  17.80
124                 Spain          81.404  26766.861770   0.40
125             Sri_Lanka          74.941   4901.338429   0.06
126                 Sudan          61.452   3181.925891   1.10
127              Suriname          70.563   8706.313971   1.00
128             Swaziland          48.718   4728.593817  25.90
129                Sweden          81.439  34395.314130   0.10
130           Switzerland          82.338  37942.468430   0.40
131            Tajikistan          67.529   1842.569444   0.20
132              Tanzania          58.199   1348.364979   5.60
133              Thailand          74.126   7982.611190   1.30
134                  Togo          57.062    933.180128   3.20
135   Trinidad_and_Tobago          70.124  17459.849750   1.50
136               Tunisia          74.515   7520.825528   0.06
137                Turkey          73.979   9148.331148   0.06
138                Uganda          54.116   1277.805600   6.50
139               Ukraine          68.494   6379.581124   1.10
140        United_Kingdom          80.170  31330.477240   0.20
141         United_States          78.531  41728.140890   0.60
142               Uruguay          77.005  12741.792020   0.50
143            Uzbekistan          68.287   2947.204002   0.10
144               Vietnam          75.181   2961.834605   0.40
145                Zambia          49.025   1476.934829  13.50
146              Zimbabwe          51.384    511.258408  14.30

[147 rows x 4 columns]

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
datos[["Life_expentacy","GDP","HIV"]].corr()

#hacemos un analisis gráfico inicial
sns.heatmap(datos[["Life_expentacy","GDP","HIV"]].corr(), square=True, annot=True)

correla = sns.pairplot(datos[["Life_expentacy","GDP","HIV"]], diag_kind="hist")

In [152]:
#Probando Modelos lineales

lm = LinearRegression()

x = datos[["GDP","HIV"]]
y = datos["Life_expentacy"]

lm.fit(x,y)

#y_pred = lm.predict(x)

#r2_score(y, y_pred)
#sns.regplot(x = "GDP", y = "Life_expentacy", data = datos)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [ ]:
#Probando modelos lineales
lm = LinearRegression()

x = datos[["GDP"]]
y = datos["Life_expentacy"]

lm.fit(x,y)
y_pred = lm.predict(x)

r2_score(y, y_pred)

In [ ]:
lm = LinearRegression()

x = datos[["HIV"]]
y = datos["Life_expentacy"]

lm.fit(x,y)
y_pred = lm.predict(x)

r2_score(y, y_pred)

In [ ]:
lm = LinearRegression()

x = datos[["GDP","HIV"]]
y = datos["Life_expentacy"]

lm.fit(x,y)
y_pred = lm.predict(x)

r2_score(y, y_pred)

In [ ]:
#LInealizando las variables
datos['GDP_log'] = np.log(datos['GDP'])
datos['HIV_log'] = np.log(datos['HIV'])

In [ ]:
lm = LinearRegression()

x = datos[["GDP_log","HIV_log"]]
y = datos["Life_expentacy"]

lm.fit(x,y)
y_pred = lm.predict(x)

r2_score(y, y_pred)

In [ ]:
#hacemos un analisis gráfico inicial
sns.heatmap(datos[["Life_expentacy","GDP_log","HIV_log"]].corr(), square=True, annot=True)

correla = sns.pairplot(datos[["Life_expentacy","GDP_log","HIV_log"]], diag_kind="hist")